### ISSUE TITLE
"Insufficient permissions to access MicroK8s"

### ISSUE THREAD

**Issue by barrettj12** [balchua/microk8s-actions#13]
The following workflow is failing:
```yaml
name: "Test MicroK8s"
on: [push, pull_request, workflow_dispatch]
jobs:
  microk8s:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up MicroK8s
      uses: balchua/microk8s-actions@v0.3.1
      with:
        channel: "1.25-strict/stable"
        addons: '["dns", "hostpath-storage"]'

    - name: Test MicroK8s
      run: |
        microk8s status
```

The second step fails with
```
Insufficient permissions to access MicroK8s.
You can either try again with sudo or add the user runner to the 'snap_microk8s' group:
    sudo usermod -a -G snap_microk8s runner
    sudo chown -R runner ~/.kube
After this, reload the user groups either via a reboot or by running 'newgrp snap_microk8s'.
```

This action should set up the user permissions correctly so that the `$USER` can access MicroK8s. Currently I can't do anything with MicroK8s. See logs [here](https://github.com/juju/juju-controller/actions/runs/3545752584/jobs/5954151913).
