### ISSUE TITLE
exec: error: timed out waiting for the condition

### ISSUE THREAD

**Issue by barrettj12** [balchua/microk8s-actions#20]
Our workflow:
```yaml
        uses: balchua/microk8s-actions@1e8e626239c2befe7cd5d258c96ae152a7259c74
        with:
          channel: "1.25-strict/stable"
          addons: '["dns", "hostpath-storage"]'
```

Logs:
```
Waiting for hostpath-storage to be ready 
exec sudo microk8s kubectl rollout status deployment/hostpath-provisioner -n kube-system --timeout=90s { silent: true }
Error: exec: error: timed out waiting for the condition
```

See the full run [here](https://github.com/juju/juju/actions/runs/6106992634/job/16573111213?pr=16212).

**Comment by balchua** [comment]
@barrettj12 thanks for logging the issue.  I haven't tried hostpath with strict confinement.  Let me try that out.  Will get back to you.

**Comment by balchua** [comment]
@barrettj12 i couldn't reproduce the error you are getting, i tried it with several MicroK8s versions.  See the jobs [here](https://github.com/balchua/microk8s-actions/actions/runs/6128120642).

But as a precaution, i increased the timeout to `120s` hoping that it will alleviate such scenario.  Do you mind trying the new release? https://github.com/balchua/microk8s-actions/releases/tag/v0.4.1

Thanks,

**Comment by barrettj12** [comment]
@balchua I'll try that, thanks. How about making that timeout configurable, so users can find their own value that works?

**Comment by balchua** [comment]
Thanks.  I was thinking of that while working on this issue.
Do you have an idea on how to present this knob to the user?
Appreciate your thoughts.

**Comment by barrettj12** [comment]
Probably just an input to the action would be fine:
```yaml
        uses: balchua/microk8s-actions@1e8e626239c2befe7cd5d258c96ae152a7259c74
        with:
          channel: "1.25-strict/stable"
          addons: '["dns", "hostpath-storage"]'
          timeout: 120s
```
