### ISSUE TITLE
Failing shell commands don't cause step to fail

### ISSUE THREAD

**Issue by knkski** [balchua/microk8s-actions#5]
If I have this in my workflow:

```yaml
    - uses: balchua/microk8s-actions@v0.2.1
      with:
        channel: 'nonexistent'
```
I will get this error message in stdout: `error: snap "microk8s" is not available on nonexistent/stable but is available ...`, but that doesn't cause the step to fail. Instead, it proceeds to wait for the API server to come up, which it never will because MicroK8s didn't get installed.

It looks like this needs to be run:

```js
set('-e');
```

It would also be nice if this got set:

```js
set('-v');
```

As it would be useful for debugging purposes
