### ISSUE TITLE
Github Actions user not added to microk8s group

### ISSUE THREAD

**Issue by knkski** [balchua/microk8s-actions#6]
I have a Github Action that looks like this:

```yaml
    - uses: balchua/microk8s-actions@v0.2.1
      with:
        channel: 'latest/stable'

    - name: Test user added
      run: id
```

That results in this output for the `Test user added` step:

```
uid=1001(runner) gid=116(docker) groups=116(docker),4(adm),101(systemd-journal)
```

I would expect to see the `microk8s` group listed in there. This might be related to #5, but it's hard to tell without the `set('-v');` option set.
